/**
 * generate-operation-docs — the single source of truth for operation counts and
 * the capability table. Reads the live OPERATIONS registry and writes
 * docs/OPERATIONS.generated.md. README and the reference paper cite these
 * numbers; generating them from code keeps a hand-typed "29" from drifting.
 *
 *   npm run docs:operations        # regenerate the file
 *   npm run docs:operations:check  # fail (exit 1) if the file is stale — CI guard
 *
 * Importing the registry needs no Personize credentials: config's client is a
 * lazy Proxy, so this runs fully offline.
 */
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { OPERATIONS, OPERATION_NAMES } from "../core/operations/registry.js";
import type { OperationEntry } from "../core/operations/types.js";

const OUTPUT_PATH = resolve(process.cwd(), "docs/OPERATIONS.generated.md");

function tally(pick: (op: OperationEntry) => string | undefined): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const name of OPERATION_NAMES) {
    const key = pick(OPERATIONS[name]) ?? "unspecified";
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}

function renderCounts(counts: Record<string, number>): string {
  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([key, n]) => `${key} (${n})`)
    .join(", ");
}

function cell(value: string | undefined): string {
  return value && value.length > 0 ? value : "—";
}

function render(): string {
  const total = OPERATION_NAMES.length;
  const byStatus = tally((op) => op.status);
  const byCategory = tally((op) => op.category);
  const byCost = tally((op) => op.cost);

  const rows = OPERATION_NAMES.map((name) => {
    const op = OPERATIONS[name];
    return [
      `\`${op.name}\``,
      cell(op.category),
      cell(op.status),
      cell(op.cost),
      op.idempotent ? "yes" : "no",
      cell(op.run_mode),
      cell((op.requires ?? []).join(", ")),
      cell((op.guidelines_required ?? []).join(", ")),
      op.acceptance ? "yes" : "—",
    ].join(" | ");
  });

  return `<!-- GENERATED by \`npm run docs:operations\` from src/core/operations/registry.ts. Do not edit by hand. -->
# Operations (generated)

**${total} registered operations.** This file is generated from the operation
registry so counts and metadata cannot drift from the code. To refresh it after
adding or changing an operation, run \`npm run docs:operations\`; \`npm run
docs:operations:check\` fails if it is stale.

- **By status:** ${renderCounts(byStatus)}
- **By category:** ${renderCounts(byCategory)}
- **By cost:** ${renderCounts(byCost)}

| Operation | Category | Status | Cost | Idempotent | Run mode | Backend caps | Guidelines required | Acceptance gate |
|---|---|---|---|---|---|---|---|---|
${rows.map((r) => `| ${r} |`).join("\n")}

_Columns reflect fields actually present on \`OperationEntry\`. Risk, side-effect,
and target-type metadata are proposed (see docs/MATURITY.md) and will appear here
once the registry carries them — this generator never invents columns._
`;
}

function main(): void {
  const check = process.argv.includes("--check");
  const content = render();

  if (check) {
    if (!existsSync(OUTPUT_PATH)) {
      console.error(`[docs:operations] ${OUTPUT_PATH} is missing. Run: npm run docs:operations`);
      process.exit(1);
    }
    const onDisk = readFileSync(OUTPUT_PATH, "utf8");
    if (onDisk !== content) {
      console.error(
        "[docs:operations] docs/OPERATIONS.generated.md is stale. Run: npm run docs:operations",
      );
      process.exit(1);
    }
    console.log(`[docs:operations] up to date (${OPERATION_NAMES.length} operations).`);
    return;
  }

  writeFileSync(OUTPUT_PATH, content);
  console.log(`[docs:operations] wrote ${OUTPUT_PATH} (${OPERATION_NAMES.length} operations).`);
}

main();
