import { z } from "zod";
import { retrieveRecords, retrieveRecord } from "../../lib/recall.js";
import { ai } from "../../lib/ai.js";
import { loadGuidelines, missingGuidelines } from "../../lib/governance.js";
import { logger } from "../../lib/logger.js";
import { createTask } from "../../lib/tasks.js";
import { todayIso, addBusinessDays, isoDate } from "../../lib/dates.js";
import { workspace } from "../../lib/workspace.js";
import type { OperationEntry } from "../types.js";

const REQUIRED_GUIDELINES = ["meeting-handoff", "brand-voice"];

const HandoffPayloadSchema = z.object({
  subject: z.string().min(5).max(200),
  headline: z.string().min(10).max(300),
  account_context: z.string().min(20).max(500),
  contact_context: z.string().min(20).max(400),
  recent_engagement: z.string().min(20).max(400),
  recommended_angle: z.string().min(10).max(300),
  open_issues: z.array(z.string().max(200)).max(5),
  urgency: z.enum(["low", "medium", "high", "critical"]),
});

async function getContact(email: string): Promise<Record<string, unknown> | null> {
  return (await retrieveRecord({ email, type: "contact" })) as Record<string, unknown> | null;
}

async function getCompany(domain: string): Promise<Record<string, unknown> | null> {
  return (await retrieveRecord({ websiteUrl: domain, type: "company" })) as Record<string, unknown> | null;
}

async function getRecentConversations(email: string): Promise<unknown[]> {
  return (await retrieveRecords({
    type: "conversation",
    conditions: [{ propertyName: "contact_email", operator: "equals", value: email }],
    logic: "AND",
    limit: 3,
  })) as unknown[];
}

async function postToSlack(webhookUrl: string, text: string, payload: z.infer<typeof HandoffPayloadSchema>): Promise<boolean> {
  try {
    const blocks = [
      { type: "header", text: { type: "plain_text", text: payload.subject } },
      { type: "section", text: { type: "mrkdwn", text: `*${payload.headline}*` } },
      { type: "section", fields: [
        { type: "mrkdwn", text: `*Account*\n${payload.account_context}` },
        { type: "mrkdwn", text: `*Contact*\n${payload.contact_context}` },
      ]},
      { type: "section", text: { type: "mrkdwn", text: `*Recent Engagement*\n${payload.recent_engagement}` } },
      { type: "section", text: { type: "mrkdwn", text: `*Recommended Angle*\n${payload.recommended_angle}` } },
      ...(payload.open_issues.length > 0 ? [{
        type: "section",
        text: { type: "mrkdwn", text: `*Open Issues*\n${payload.open_issues.map((i) => `• ${i}`).join("\n")}` },
      }] : []),
      { type: "context", elements: [{ type: "mrkdwn", text: `Urgency: *${payload.urgency}* · Generated by crm-ai-operators` }] },
    ];

    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text, blocks }),
    });
    return response.ok;
  } catch (error) {
    logger.warn("Slack webhook call failed", { error: error instanceof Error ? error.message : String(error) });
    return false;
  }
}

export const actNotifyRepHandoff: OperationEntry = {
  name: "act.notify-rep-handoff",
  mode: "operation",
  description: "Build a structured handoff payload per the meeting-handoff guideline and route it to Slack webhook or a rep task. Creates an ack task either way.",
  category: "act",
  status: "live",
  idempotent: false,
  cost: "low",
  run_mode: "on-trigger",
  guidelines_required: REQUIRED_GUIDELINES,
  run: async (input, context) => {
    const inputObj = (input ?? {}) as { contact_email?: string; email?: string; trigger?: string };
    // Dispatcher per-record/chain routes send `email`; standalone/CLI callers may pass `contact_email`.
    const contactEmail = inputObj.email ?? inputObj.contact_email;
    const trigger = inputObj.trigger ?? "unspecified";

    if (!contactEmail) {
      return {
        ok: false,
        runId: context.runId,
        operation: "act.notify-rep-handoff",
        dryRun: context.dryRun,
        summary: "contact_email is required. Pass it as input: { contact_email: 'name@company.com', trigger: 'Positive interest reply' }",
      };
    }

    const guidelines = await loadGuidelines(REQUIRED_GUIDELINES);
    const missing = missingGuidelines(guidelines);
    if (missing.length > 0) {
      return {
        ok: false,
        runId: context.runId,
        operation: "act.notify-rep-handoff",
        dryRun: context.dryRun,
        summary: `Missing required guidelines: ${missing.join(", ")}. Run setup.apply first.`,
        metrics: { missing_guidelines: missing },
      };
    }

    const contact = await getContact(contactEmail);
    if (!contact) {
      return {
        ok: false,
        runId: context.runId,
        operation: "act.notify-rep-handoff",
        dryRun: context.dryRun,
        summary: `Contact not found in Personize: ${contactEmail}`,
      };
    }

    const [company, conversations] = await Promise.all([
      contact.company_domain ? getCompany(contact.company_domain as string) : Promise.resolve(null),
      getRecentConversations(contactEmail),
    ]);

    const recordContext = JSON.stringify({
      contact,
      company,
      trigger,
      recent_conversations: conversations,
    }, null, 2);

    if (context.dryRun) {
      logger.info("[DRY RUN] Would send rep handoff", { email: contactEmail, trigger });
      return {
        ok: true,
        runId: context.runId,
        operation: "act.notify-rep-handoff",
        dryRun: true,
        status: "live",
        summary: `[DRY RUN] Would send handoff for ${contactEmail} (trigger: ${trigger}).`,
      };
    }

    const result = await ai({
      instructions: `Build a rep handoff notification payload for this contact. The trigger was: "${trigger}". Be specific — cite actual facts.

Contact + company + recent conversations:
${recordContext}`,
      context: `# Meeting Handoff\n\n${guidelines["meeting-handoff"]}\n\n---\n\n# Brand Voice\n\n${guidelines["brand-voice"]}`,
      outputs: HandoffPayloadSchema,
      temperature: 0.3,
      maxTokens: 800,
    });

    const payload = result.output;
    const slackWebhookUrl = process.env["SLACK_WEBHOOK_URL"];
    let channel = "task";
    let notified = false;

    if (slackWebhookUrl) {
      const text = `Handoff: ${payload.subject} — ${contactEmail}`;
      notified = await postToSlack(slackWebhookUrl, text, payload);
      if (notified) channel = "slack";
    }

    // Always create an ack task for the rep regardless of channel
    await createTask({
      title: `[Handoff] ${payload.subject}`,
      task_type: "rep-handoff",
      assigned_to: "rep",
      priority: payload.urgency === "critical" ? "urgent" : "high",
      due_date: isoDate(addBusinessDays(new Date(), 1)),
      notes: JSON.stringify({ trigger, payload, channel }),
      custom_key_name: "email",
      custom_key_value: contactEmail,
      created_by: "act.notify-rep-handoff",
    });

    await workspace.appendUpdate(
      { email: contactEmail },
      {
        author: "act.notify-rep-handoff",
        type: "handoff",
        summary: `Rep handoff sent via ${channel} — trigger: ${trigger}`,
        details: { trigger, channel, urgency: payload.urgency, subject: payload.subject },
      },
      "contact",
    );

    return {
      ok: true,
      runId: context.runId,
      operation: "act.notify-rep-handoff",
      dryRun: context.dryRun,
      status: "live",
      summary: `Handoff delivered via ${channel} for ${contactEmail} (trigger: ${trigger}, urgency: ${payload.urgency}).`,
      metrics: { contact_email: contactEmail, trigger, channel, urgency: payload.urgency, slack_notified: notified },
    };
  },
};
